// =====================================================================
// DUSTFALL — Canonical data, centralized from DUSTFALL_BIBLE.md (Phase 1)
// Standalone module: browser globals + Node/Electron export, zero deps,
// works offline from local files (SHIP TARGET safe). Consumed by the
// World Map / Town / Battle / Results scenes. Merge into data.js when the
// scene refactor lands; kept separate here to avoid churning data.js.
// =====================================================================

// ---- The Pantheon: 6 gods, faction, corruption, divine ability (bible §1, §4) ----
const GODS = [
  {
    id: "vulcan",
    name: "Vulcan",
    title: "The Forgefather",
    origin: "Roman",
    domain: "Forge, fire, industry",
    faction: "Forgeworks Syndicate",
    corruption: "Dehumanization",
    color: "#d4a843",
    divine: {
      name: "Forge Strike",
      desc: "Superheated melee, ignores armor.",
      dmg: [8, 14],
      apCost: 3,
    },
  },
  {
    id: "perun",
    name: "Perun",
    title: "The Thunderer",
    origin: "Slavic",
    domain: "Thunder, war, justice",
    faction: "The Regulators",
    corruption: "Fanaticism",
    color: "#5b7faa",
    divine: {
      name: "Thunderbolt",
      desc: "Ranged lightning, guaranteed hit, stuns 1 turn.",
      dmg: [6, 12],
      apCost: 3,
      stun: 1,
    },
  },
  {
    id: "samedi",
    name: "Baron Samedi",
    title: "The Gatekeeper",
    origin: "Haitian Vodou",
    domain: "Death, crossroads, resurrection",
    faction: "The Harrowed",
    corruption: "Undeath",
    color: "#6b3fa0",
    divine: {
      name: "Death's Touch",
      desc: "Drain 5-8 dmg, heal self full.",
      dmg: [5, 8],
      apCost: 3,
      lifesteal: true,
    },
  },
  {
    id: "coyote",
    name: "Coyote",
    title: "The Trickster",
    origin: "Native American",
    domain: "Trickery, change, the wild",
    faction: "The Dust Walkers",
    corruption: "Chaos",
    color: "#c85a3a",
    divine: {
      name: "Mirage",
      desc: "Illusory decoy draws attacks for 2 turns.",
      apCost: 3,
      decoy: 2,
    },
  },
  {
    id: "anansi",
    name: "Anansi",
    title: "The Weaver",
    origin: "West African",
    domain: "Stories, cunning, knowledge",
    faction: "Los Tejedores",
    corruption: "Manipulation",
    color: "#7a9a4a",
    divine: {
      name: "Weaver's Curse",
      desc: "Target attacks nearest ally for 1 turn.",
      apCost: 3,
      confuse: 1,
    },
  },
  {
    id: "sleeping",
    name: "The Sleeping One",
    title: "The Final Threat",
    origin: "Primordial",
    domain: "Endings, the deep earth",
    faction: "The Hollow Court",
    corruption: "Annihilation",
    color: "#2a3a2a",
    divine: {
      name: "Hollow Dread",
      desc: "Fear aura, all foes lose accuracy.",
      apCost: 3,
      fear: true,
    },
  },
];

// ---- Weapons / Armor / Consumables (bible §6 Outfitter) ----
const WEAPONS = [
  {
    id: "revolver",
    name: "Revolver",
    range: 5,
    wmin: 4,
    wmax: 8,
    accuracy: 75,
    apCost: 2,
    cost: 60,
    note: "Reliable, cheap",
  },
  {
    id: "rifle",
    name: "Rifle",
    range: 7,
    wmin: 5,
    wmax: 10,
    accuracy: 70,
    apCost: 2,
    cost: 120,
    note: "Long range, slow",
  },
  {
    id: "shotgun",
    name: "Shotgun",
    range: 3,
    wmin: 6,
    wmax: 12,
    accuracy: 65,
    apCost: 2,
    cost: 110,
    note: "Devastating close",
  },
  {
    id: "repeater",
    name: "Repeater",
    range: 6,
    wmin: 3,
    wmax: 6,
    accuracy: 80,
    apCost: 1,
    cost: 90,
    note: "Fast, light",
  },
  {
    id: "ashfall_pistol",
    name: "Ashfall Pistol",
    range: 5,
    wmin: 5,
    wmax: 12,
    accuracy: 58,
    apCost: 2,
    cost: 180,
    pierce: true,
    note: "Armor-piercing",
  },
  {
    id: "steam_cannon",
    name: "Steam Cannon",
    range: 6,
    wmin: 7,
    wmax: 12,
    accuracy: 55,
    apCost: 2,
    cost: 200,
    archetype: "tinkerer",
    note: "Heavy",
  },
  {
    id: "hex_focus",
    name: "Hex Focus",
    range: 4,
    wmin: 3,
    wmax: 7,
    accuracy: 70,
    apCost: 2,
    cost: 160,
    ignoreCover: true,
    archetype: "hexslinger",
    note: "Ignores cover",
  },
];
const ARMOR = [
  { id: "leather_duster", name: "Leather Duster", def: 2, spd: 0, cost: 50 },
  {
    id: "reinforced_vest",
    name: "Reinforced Vest",
    def: 4,
    spd: -1,
    cost: 140,
  },
  {
    id: "ashfall_plating",
    name: "Ashfall Plating",
    def: 6,
    spd: -2,
    cost: 260,
  },
  {
    id: "blessed_vestments",
    name: "Blessed Vestments",
    def: 3,
    spd: 0,
    cost: 150,
    divineResist: 10,
  },
  {
    id: "clockwork_exo",
    name: "Clockwork Exo",
    def: 5,
    spd: 0,
    cost: 400,
    archetype: "tinkerer",
  },
];
const CONSUMABLES = [
  { id: "bandages", name: "Bandages", cost: 15, effect: "heal", amount: 8 },
  {
    id: "ashfall_charge",
    name: "Ashfall Charge",
    cost: 40,
    effect: "aoe",
    dmg: [6, 10],
    radius: 2,
  },
  {
    id: "smelling_salts",
    name: "Smelling Salts",
    cost: 25,
    effect: "revive",
    amount: 5,
  },
  {
    id: "tonic_vigor",
    name: "Tonic of Vigor",
    cost: 30,
    effect: "buff",
    stat: "vigor",
    amount: 2,
  },
  {
    id: "holy_water",
    name: "Holy Water",
    cost: 35,
    effect: "antiundead",
    mult: 2,
  },
  {
    id: "coyote_dust",
    name: "Coyote Dust",
    cost: 50,
    effect: "invis",
    turns: 1,
  },
];

// ---- Bestiary (bible §7) — combat-ready; q/r assigned at spawn ----
// behavior: melee|ranged|swarm|flanks|cover|blinker|bomber|hexer|summoner|aoe|selfbuff|turret|possess|regen|fear|clones|confuse|webs|phase2
const BESTIARY = {
  t1: [
    {
      id: "walkin_dead",
      name: "Walkin' Dead",
      tier: 1,
      faction: "samedi",
      icon: "💀",
      hp: 12,
      quick: 3,
      str: 7,
      aim: 55,
      rng: 1,
      wmin: 4,
      wmax: 7,
      color: "#7c9a6a",
      behavior: ["melee", "swarm"],
      xp: 8,
    },
    {
      id: "rattlesnake",
      name: "Rattlesnake",
      tier: 1,
      faction: "coyote",
      icon: "🤠",
      hp: 16,
      quick: 5,
      str: 5,
      aim: 72,
      rng: 6,
      wmin: 4,
      wmax: 8,
      color: "#b5452a",
      behavior: ["ranged", "cover"],
      xp: 10,
    },
    {
      id: "coyote_beast",
      name: "Coyote",
      tier: 1,
      faction: "wild",
      icon: "🐺",
      hp: 8,
      quick: 7,
      str: 5,
      aim: 65,
      rng: 1,
      wmin: 3,
      wmax: 5,
      color: "#b88a4a",
      behavior: ["melee", "flanks"],
      xp: 7,
    },
    {
      id: "forge_sentry",
      name: "Forgeworks Sentry",
      tier: 1,
      faction: "vulcan",
      icon: "🤖",
      hp: 20,
      quick: 3,
      str: 6,
      aim: 68,
      rng: 5,
      wmin: 4,
      wmax: 8,
      color: "#8899aa",
      behavior: ["ranged"],
      xp: 12,
    },
    {
      id: "dust_devil_e",
      name: "Dust Devil",
      tier: 1,
      faction: "coyote",
      icon: "🌪",
      hp: 10,
      quick: 6,
      str: 4,
      aim: 60,
      rng: 2,
      wmin: 3,
      wmax: 6,
      color: "#c4a265",
      behavior: ["blinker", "aoe"],
      xp: 10,
    },
  ],
  t2: [
    {
      id: "harrowed_gun",
      name: "Harrowed Gunfighter",
      tier: 2,
      faction: "samedi",
      icon: "🔫",
      hp: 18,
      quick: 6,
      str: 5,
      aim: 74,
      rng: 5,
      wmin: 5,
      wmax: 8,
      color: "#5a8a8a",
      behavior: ["ranged", "blinker"],
      xp: 18,
    },
    {
      id: "dynamite_bandit",
      name: "Dynamite Bandit",
      tier: 2,
      faction: "coyote",
      icon: "🧨",
      hp: 14,
      quick: 5,
      str: 5,
      aim: 70,
      rng: 4,
      wmin: 4,
      wmax: 7,
      color: "#d4763a",
      behavior: ["bomber"],
      xp: 16,
    },
    {
      id: "ashfall_golem",
      name: "Ashfall Golem",
      tier: 2,
      faction: "vulcan",
      icon: "🗿",
      hp: 30,
      quick: 2,
      str: 9,
      aim: 65,
      rng: 1,
      wmin: 6,
      wmax: 11,
      color: "#a0522d",
      behavior: ["melee", "aoe"],
      xp: 25,
    },
    {
      id: "dust_witch",
      name: "Dust Witch",
      tier: 2,
      faction: "anansi",
      icon: "🃏",
      hp: 12,
      quick: 5,
      str: 4,
      aim: 72,
      rng: 4,
      wmin: 3,
      wmax: 6,
      color: "#9a6ab8",
      behavior: ["hexer", "summoner"],
      xp: 20,
    },
    {
      id: "thunder_zealot",
      name: "Thunder Zealot",
      tier: 2,
      faction: "perun",
      icon: "⚡",
      hp: 22,
      quick: 4,
      str: 7,
      aim: 73,
      rng: 5,
      wmin: 5,
      wmax: 9,
      color: "#5b7faa",
      behavior: ["ranged", "selfbuff"],
      xp: 22,
    },
  ],
  t3: [
    {
      id: "the_deacon",
      name: "The Deacon",
      tier: 3,
      boss: true,
      faction: "samedi",
      icon: "⛪",
      hp: 40,
      quick: 4,
      str: 6,
      aim: 74,
      rng: 5,
      wmin: 5,
      wmax: 9,
      color: "#6b3fa0",
      behavior: ["summoner", "hexer", "phase2"],
      xp: 60,
    },
    {
      id: "iron_foreman",
      name: "The Iron Foreman",
      tier: 3,
      boss: true,
      faction: "vulcan",
      icon: "⚙",
      hp: 60,
      quick: 1,
      str: 10,
      aim: 70,
      rng: 6,
      wmin: 7,
      wmax: 12,
      color: "#d4a843",
      behavior: ["turret", "aoe", "phase2"],
      xp: 80,
    },
    {
      id: "hollow_man",
      name: "The Hollow Man",
      tier: 3,
      boss: true,
      faction: "sleeping",
      icon: "👁",
      hp: 35,
      quick: 7,
      str: 6,
      aim: 72,
      rng: 3,
      wmin: 4,
      wmax: 8,
      color: "#2a3a2a",
      behavior: ["possess", "regen", "fear"],
      xp: 70,
    },
    {
      id: "coyotes_shadow",
      name: "Coyote's Shadow",
      tier: 3,
      boss: true,
      faction: "coyote",
      icon: "🌑",
      hp: 25,
      quick: 8,
      str: 5,
      aim: 75,
      rng: 4,
      wmin: 4,
      wmax: 7,
      color: "#c85a3a",
      behavior: ["clones", "blinker"],
      xp: 65,
    },
    {
      id: "the_weaver",
      name: "The Weaver",
      tier: 3,
      boss: true,
      faction: "anansi",
      icon: "🕷",
      hp: 30,
      quick: 5,
      str: 5,
      aim: 73,
      rng: 5,
      wmin: 4,
      wmax: 8,
      color: "#7a9a4a",
      behavior: ["confuse", "webs"],
      xp: 70,
    },
  ],
};

// ---- per-archetype active abilities (bible §4) ----
const ABILITIES = {
  gunslinger: [
    { name: "Fan the Hammer", apCost: 3, desc: "3 shots at -10% acc each" },
    {
      name: "Dead Eye",
      apCost: 2,
      desc: "Next shot guaranteed crit if it hits",
    },
  ],
  hexslinger: [
    { name: "Hex Bolt", apCost: 2, desc: "Ranged magic, ignores cover" },
    { name: "Soul Drain", apCost: 2, desc: "Damage + heal self 50%" },
    { name: "Jinx", apCost: 1, desc: "-20% acc on target, 2 turns" },
  ],
  tinkerer: [
    { name: "Deploy Turret", apCost: 3, desc: "Auto-firing turret, 8 HP" },
    { name: "Ashfall Grenade", apCost: 2, desc: "AoE 4-8 dmg, 2-tile radius" },
    { name: "Overclock", apCost: 1, desc: "Ally +2 AP this turn" },
  ],
  preacher: [
    { name: "Lay on Hands", apCost: 2, desc: "Heal ally 5-10" },
    { name: "Smite", apCost: 2, desc: "+50% dmg vs undead" },
    { name: "Sanctuary", apCost: 3, desc: "Allies +20% def, 2 turns" },
  ],
  lawdog: [
    { name: "Hold the Line", apCost: 2, desc: "+30% def, taunt" },
    { name: "Rallying Cry", apCost: 2, desc: "Allies +10% acc, 2 turns" },
    { name: "Called Shot", apCost: 3, desc: "Guaranteed hit, cripple limb" },
  ],
  drifter: [
    {
      name: "Dust Devil",
      apCost: 2,
      desc: "Move through enemies, no overwatch",
    },
    { name: "Scavenge", apCost: 1, desc: "Search adjacent tile for items" },
  ],
};

if (typeof window !== "undefined") {
  window.DUSTFALL_CANON = {
    GODS,
    WEAPONS,
    ARMOR,
    CONSUMABLES,
    BESTIARY,
    ABILITIES,
  };
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = { GODS, WEAPONS, ARMOR, CONSUMABLES, BESTIARY, ABILITIES };
}
