// =============================================
// DUSTFALL — OVERWORLD MAP DATA (Phase 2)
// The real US Southwest: Oregon -> Mexican border (N-S), offshore Catalina -> Texas (E-W).
// x,y are normalized 0..1 (x = west->east, y = north->south) roughly matching real geography.
// god = dominant deity/faction (tints the node); lore hooks each city's real fame to the mythology.
// svc = town services present. tier = encounter difficulty in/around the node.
// =============================================

const WORLD_NODES = [
  // --- Pacific NW / Northern California ---
  {
    id: "portland",
    name: "Portland",
    x: 0.085,
    y: 0.045,
    god: "coyote",
    region: "Trickster's Maze",
    tier: 1,
    svc: ["saloon", "outfitter", "stable"],
    lore: "Where the rails end and the wild begins — Coyote walks the rain-soaked timberline.",
  },
  {
    id: "sanfran",
    name: "San Francisco",
    x: 0.05,
    y: 0.345,
    god: "anansi",
    region: "The Flats",
    tier: 2,
    svc: ["saloon", "outfitter", "shrine", "doc"],
    lore: "The Barbary Coast — every story bought and sold. Anansi keeps the ledger.",
  },
  {
    id: "sacramento",
    name: "Sacramento",
    x: 0.095,
    y: 0.31,
    god: "vulcan",
    region: "The Forgeworks",
    tier: 1,
    svc: ["saloon", "outfitter", "forge"],
    lore: "Gold built it; the Forgeworks Syndicate runs the smelters now.",
  },
  {
    id: "virginia",
    name: "Virginia City",
    x: 0.17,
    y: 0.32,
    god: "vulcan",
    region: "The Forgeworks",
    tier: 2,
    svc: ["saloon", "forge", "shrine"],
    lore: "The Comstock Lode — a mountain hollowed for silver. Vulcan loves a deep wound in the earth.",
  },
  {
    id: "reno",
    name: "Reno",
    x: 0.165,
    y: 0.3,
    god: "coyote",
    region: "Trickster's Maze",
    tier: 1,
    svc: ["saloon", "outfitter", "stable"],
    lore: "The biggest little city — fortunes made and unmade on a card turn. Coyote deals.",
  },
  {
    id: "carson",
    name: "Carson City",
    x: 0.165,
    y: 0.335,
    god: "perun",
    region: "Thunderheart",
    tier: 1,
    svc: ["saloon", "marshal", "shrine"],
    lore: "The capital's mint stamps the coin of law. The Regulators keep their ledgers here.",
  },

  // --- Great Basin / Utah ---
  {
    id: "saltlake",
    name: "Salt Lake City",
    x: 0.33,
    y: 0.235,
    god: "perun",
    region: "Thunderheart",
    tier: 2,
    svc: ["saloon", "outfitter", "shrine", "marshal"],
    lore: "A city built on covenant and order — Perun’s fanatics call it the promised ground.",
  },

  // --- Southern California / Mojave ---
  {
    id: "catalina",
    name: "Catalina",
    x: 0.1,
    y: 0.56,
    god: "anansi",
    region: "The Flats",
    tier: 1,
    svc: ["saloon", "outfitter"],
    start: true,
    lore: "Your crew’s last safe harbor off-shore. Smugglers’ island — the story starts here.",
  },
  {
    id: "losangeles",
    name: "Los Angeles",
    x: 0.125,
    y: 0.52,
    god: "anansi",
    region: "The Flats",
    tier: 2,
    svc: ["saloon", "outfitter", "shrine", "doc", "stable"],
    lore: "A boomtown of light and lies sprawling to the sea — every faction wants its ear.",
  },
  {
    id: "sandiego",
    name: "San Diego",
    x: 0.14,
    y: 0.605,
    god: "perun",
    region: "Thunderheart",
    tier: 1,
    svc: ["saloon", "outfitter", "marshal"],
    lore: "The border garrison — guns pointed south, law pointed everywhere.",
  },
  {
    id: "deathvalley",
    name: "Death Valley",
    x: 0.19,
    y: 0.44,
    god: "samedi",
    region: "The Boneyard",
    tier: 3,
    svc: ["shrine"],
    lore: "The lowest, hottest grave on the continent. Baron Samedi’s twilight pools here.",
  },
  {
    id: "salton",
    name: "Salton Sea",
    x: 0.18,
    y: 0.585,
    god: "sleeper",
    region: "The Scorch",
    tier: 3,
    svc: [],
    lore: "A dead sea that should not exist, fish-bones to the horizon. The Sleeping One dreams beneath it.",
  },

  // --- Nevada interior ---
  {
    id: "vegas",
    name: "Las Vegas",
    x: 0.245,
    y: 0.46,
    god: "coyote",
    region: "Trickster's Maze",
    tier: 2,
    svc: ["saloon", "outfitter", "shrine", "stable"],
    lore: "A mirage of neon in the dust where every bet is rigged. Coyote and Anansi split the take.",
  },
  {
    id: "area51",
    name: "Groom Lake",
    x: 0.26,
    y: 0.42,
    god: "sleeper",
    region: "The Scorch",
    tier: 3,
    svc: [],
    lore: "A dry lakebed the maps refuse to name. Whatever the army buried, it is awake.",
  },
  {
    id: "hoover",
    name: "Hoover Dam",
    x: 0.27,
    y: 0.475,
    god: "vulcan",
    region: "The Forgeworks",
    tier: 2,
    svc: ["forge"],
    lore: "A wall of poured stone that bends a river to the will of machines. Vulcan’s masterpiece.",
  },

  // --- Arizona ---
  {
    id: "sedona",
    name: "Sedona",
    x: 0.335,
    y: 0.5,
    god: "coyote",
    region: "Trickster's Maze",
    tier: 2,
    svc: ["saloon", "shrine"],
    lore: "Red rock that hums and canyons that loop back on themselves. Coyote’s country, plainly.",
  },
  {
    id: "phoenix",
    name: "Phoenix",
    x: 0.33,
    y: 0.56,
    god: "vulcan",
    region: "The Forgeworks",
    tier: 2,
    svc: ["saloon", "outfitter", "forge", "doc"],
    lore: "Risen from its own ashes in the valley of heat — the Syndicate’s desert capital.",
  },
  {
    id: "tucson",
    name: "Tucson",
    x: 0.37,
    y: 0.62,
    god: "perun",
    region: "Thunderheart",
    tier: 1,
    svc: ["saloon", "outfitter", "marshal", "stable"],
    lore: "Old presidio town on the southern road — the last law before the line.",
  },
  {
    id: "tombstone",
    name: "Tombstone",
    x: 0.405,
    y: 0.645,
    god: "samedi",
    region: "The Boneyard",
    tier: 2,
    svc: ["saloon", "marshal"],
    lore: "The town too tough to die, named for a grave. Its gunfighters keep coming back wrong.",
  },

  // --- New Mexico ---
  {
    id: "losalamos",
    name: "Los Alamos",
    x: 0.48,
    y: 0.46,
    god: "vulcan",
    region: "The Forgeworks",
    tier: 3,
    svc: ["forge"],
    lore: "The hidden mesa-forge where they split the very atom of Ashfall. Vulcan’s most dangerous altar.",
  },
  {
    id: "albuquerque",
    name: "Albuquerque",
    x: 0.49,
    y: 0.52,
    god: "coyote",
    region: "Trickster's Maze",
    tier: 2,
    svc: ["saloon", "outfitter", "shrine", "stable"],
    lore: "A crossroads of the high desert road — nothing here goes where the sign says.",
  },
  {
    id: "roswell",
    name: "Roswell",
    x: 0.52,
    y: 0.6,
    god: "sleeper",
    region: "The Scorch",
    tier: 3,
    svc: ["saloon", "shrine"],
    lore: "Something fell from the sky and the army hauled it off in crates. The Sleeping One has cousins.",
  },

  // --- West Texas / Texas ---
  {
    id: "elpaso",
    name: "El Paso",
    x: 0.525,
    y: 0.665,
    god: "samedi",
    region: "The Boneyard",
    tier: 2,
    svc: ["saloon", "outfitter", "marshal"],
    lore: "The pass between two countries and two worlds — the dead cross both ways.",
  },
  {
    id: "marfa",
    name: "Marfa",
    x: 0.6,
    y: 0.66,
    god: "coyote",
    region: "Trickster's Maze",
    tier: 2,
    svc: ["saloon", "shrine"],
    lore: "Lights drift over the basin at night that no lantern made. Coyote, laughing in the dark.",
  },
  {
    id: "sanantonio",
    name: "San Antonio",
    x: 0.74,
    y: 0.665,
    god: "perun",
    region: "Thunderheart",
    tier: 2,
    svc: ["saloon", "outfitter", "marshal", "doc"],
    lore: "Remember the mission-fort where men chose to die for a line on a map. Perun remembers.",
  },
  {
    id: "austin",
    name: "Austin",
    x: 0.745,
    y: 0.62,
    god: "anansi",
    region: "The Flats",
    tier: 2,
    svc: ["saloon", "outfitter", "shrine", "forge", "stable"],
    lore: "The eastern capital where every faction keeps a quiet office. The frontier’s loud edge.",
  },
];

// Paths: [a, b, risk]  risk 1=road(safe) 2=trail 3=wilderness. Travel time derives from distance.
const WORLD_EDGES = [
  ["portland", "sacramento", 2],
  ["sacramento", "sanfran", 1],
  ["sacramento", "virginia", 2],
  ["sacramento", "reno", 2],
  ["reno", "virginia", 1],
  ["reno", "carson", 1],
  ["virginia", "carson", 1],
  ["carson", "saltlake", 3],
  ["sanfran", "losangeles", 2],
  ["losangeles", "catalina", 1],
  ["losangeles", "sandiego", 1],
  ["losangeles", "deathvalley", 3],
  ["deathvalley", "vegas", 2],
  ["sandiego", "salton", 2],
  ["salton", "vegas", 3],
  ["vegas", "area51", 2],
  ["vegas", "hoover", 1],
  ["area51", "hoover", 2],
  ["hoover", "sedona", 2],
  ["sedona", "phoenix", 2],
  ["phoenix", "tucson", 1],
  ["tucson", "tombstone", 2],
  ["saltlake", "hoover", 3],
  ["saltlake", "losalamos", 3],
  ["hoover", "losalamos", 3],
  ["phoenix", "losalamos", 3],
  ["losalamos", "albuquerque", 1],
  ["albuquerque", "roswell", 2],
  ["roswell", "elpaso", 2],
  ["tombstone", "elpaso", 2],
  ["elpaso", "marfa", 2],
  ["marfa", "sanantonio", 3],
  ["sanantonio", "austin", 1],
  ["albuquerque", "austin", 3],
  ["vegas", "sedona", 3],
  ["losangeles", "vegas", 2],
];

if (typeof window !== "undefined") {
  window.DFDATA = window.DFDATA || {};
  window.DFDATA.WORLD_NODES = WORLD_NODES;
  window.DFDATA.WORLD_EDGES = WORLD_EDGES;
}
